name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      # If this is setup to true, we will bypass staging and deploy directly to production
      hotfix:
        description: 'Hotfix'
        required: false
        type: boolean
        default: false

jobs:
  integrity:
    name: Code Integrity
    uses: ./.github/workflows/integrity.yml

  deploy-to-staging:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.hotfix != 'true'
    name: Build and deploy to Staging
    runs-on: ubuntu-latest
    needs: integrity
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Build Staging
        uses: ./.github/actions/build
        with:
          environment: staging

      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: build-staging
          path: build/

      - name: Deploy to staging
        run: |
          echo "Deploy to staging"

  deploy-to-production:
     # This job runs if it's a hotfix or after successful staging deployment
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.hotfix == 'true') ||
      (github.event_name == 'workflow_dispatch' && needs.deploy-to-staging.result == 'success')
    name: Build and deploy to Production
    runs-on: ubuntu-latest
    needs: [integrity, deploy-to-staging]
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Build Production
        uses: ./.github/actions/build
        with:
          environment: production

      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: build-production
          path: build/

      - name: Deploy to prod
        run: |
          echo "Deploy to prod"