name: Deploy App

on: workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Start test
        run: npm run test

  build:
    name: Build and deploy
    runs-on: ubuntu-20.04
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run typecheck
        run: npm run typecheck

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ${{ env.ENV_FILE_PATH }}
          load-mode: strict

      - name: Build
        run: npm run build

      - name: Echo some env variables
        run: |
          echo "Variable 1: ${{ env.NODE_ENV }}"
