name: On main merge workflow

on:
  push:
    branches: 
      - with-promotions # Trigger the workflow on push to the main branch
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        type: choice
        options:
        - 'staging'
        - 'production'
        default: 'staging'

jobs:
  integrity:
    name: Code Integrity
    uses: ./.github/workflows/integrity.yml
  
  build-staging:
    name: Build Staging
    uses: ./.github/workflows/build.yml
    with:
      environment: staging

  deploy-to-staging:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-staging
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: build-staging
          path: build/

      - name: Deploy to staging
        run: |
          echo "Deploy to staging"

  build-production:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
    name: Build Production
    needs: deploy-to-staging
    uses: ./.github/workflows/build.yml
    environment: production
    with:
      environment: production

  deploy-to-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-production
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: build-production
          path: build/

      - name: Deploy to prod
        run: |
          echo "Deploy to prod"